version: 2
updates:
- package-ecosystem: "github-actions"
  directory: "/.github"
  schedule:
    interval: "weekly"
    day: "tuesday"
    time: "07:00"
    timezone: "Europe/Amsterdam"
  reviewers:
  - "strickvl"
  labels:
  - "dependencies"
  - "internal"
  target-branch: "develop"
