[files]
extend-exclude = [
    "*.json",
    "*.js",
    "*.ipynb",
    "src/zenml/zen_stores/migrations/versions/",
    "tests/unit/materializers/test_built_in_materializer.py",
    "tests/integration/functional/cli/test_pipeline.py",
    "src/zenml/zen_server/dashboard/",
    "examples/llm_finetuning/lit_gpt/"
]

[default.extend-identifiers]
HashiCorp = "HashiCorp"
NDArray = "NDArray"
K_Scatch = "K_Scatch"
MCAGA1UECgwZQW1hem9uIFdlYiBTZXJ2aWNlcywgSW5jLjETMBEGA1UECwwKQW1h = "MCAGA1UECgwZQW1hem9uIFdlYiBTZXJ2aWNlcywgSW5jLjETMBEGA1UECwwKQW1h"
VQQGEwJVUzEQMA4GA1UEBwwHU2VhdHRsZTETMBEGA1UECAwKV2FzaGluZ3RvbjEi = "VQQGEwJVUzEQMA4GA1UEBwwHU2VhdHRsZTETMBEGA1UECAwKV2FzaGluZ3RvbjEi"
MDEyOk9yZ2FuaXphdGlvbjg4Njc2OTU1 = "MDEyOk9yZ2FuaXphdGlvbjg4Njc2OTU1"

[default.extend-words]
# Don't correct the surname "Teh"
aks = "aks"
hashi = "hashi"
womens = "womens"
prepend = "prepend"
prepended = "prepended"
goes = "goes"
bare = "bare"
prepending = "prepending"
prev = "prev"
creat = "creat"
ret = "ret"
daa = "daa"
arange = "arange"
cachable = "cachable"

[default]
locale = "en-us"
