name: hihigcp
provider: gcp
create_cloudsql: true
username: default
password: zenml
log_level: ERROR
ingress_path: jayesh-hihi-gcp
create_ingress_controller: false
ingress_controller_hostname: 35.198.73.40.nip.io
project_id: zenml-demos
zenmlserver_image_tag: server-test-three

namespace: test

