{{- range $name, $worker := .Values.workerDeployments }}
{{- if or (not (hasKey $worker "enabled")) $worker.enabled }}
{{- if $worker.secretEnvironment }}
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "zenml.fullname" $ }}-worker-{{ $name }}
  labels:
    {{- include "zenml.labels" $ | nindent 4 }}
    app.kubernetes.io/component: worker-{{ $name }}
data:
  {{- range $key, $value := $worker.secretEnvironment }}
  {{ $key }}: {{ $value | b64enc | quote }}
  {{- end }}
{{- end }}
{{- end }}
{{- end }}
