# environment configuration
settings:
  resources:
    memory: 64GB
  docker:
    parent_image: "zenml-quickstart:0.64.0-py3.11"
#  orchestrator.sagemaker:
#    instance_type: ml.p3.2xlarge

# configuration of the Model Control Plane
model:
  name: YeOldeEnglishTranslator
  description: Model to translate from old to modern english
  tags: ["quickstart", "llm"]

# Configure the pipeline
parameters:
  # model_type: "t5-small"  # Choose between t5-small and t5-large
  num_train_epochs: 30
  per_device_train_batch_size: 4
  gradient_accumulation_steps: 1
  dataloader_num_workers: 0
