apiVersion: v2
name: zenml
version: "0.66.0"
description: Open source MLOps framework for portable production ready ML pipelines
keywords:
- mlops
- zenml
- server
home: https://zenml.io
sources:
- https://github.com/zenml-io/zenml
icon: https://raw.githubusercontent.com/zenml-io/zenml/main/docs/book/.gitbook/assets/zenml_logo.png
