# environment configuration
settings:
  docker:
    required_integrations:
      - sklearn
      - pandas
    requirements:
      - pyarrow

# configuration of the Model Control Plane
model:
  name: breast_cancer_classifier
  version: sgd
  license: Apache 2.0
  description: A breast cancer classifier
  tags: ["breast_cancer", "classifier"]

# Configure the pipeline
parameters:
  model_type: "sgd"  # Choose between rf/sgd
