apiVersion: rbac.authorization.k8s.io/v1
# This cluster role binding allows the tfx service account to edit pods
# For Kubeflow compatibility, we bind this role to both the default and
# kubeflow namespace. This may be removed in a future version.
kind: ClusterRoleBinding
metadata:
  name: zenml-edit
subjects:
- kind: ServiceAccount
  name: zenml-service-account
  namespace: default
- kind: ServiceAccount
  name: zenml-service-account
  namespace: zenml
roleRef:
  kind: ClusterRole
  name: edit
  apiGroup: rbac.authorization.k8s.io
