name: Build, Lint, Unit & Integration Test

on:
  workflow_dispatch:
  workflow_call:
  push:
    branches: ["main", "develop"]
    paths-ignore: ["docs/**", "docker/**", "*", "!pyproject.toml", "**.md"]
  pull_request:
    types: [opened, synchronize, ready_for_review]
    paths-ignore: ["docs/**", "docker/**", "*", "!pyproject.toml", "**.md"]

concurrency:
  # New commit on branch cancels running workflows of the same branch
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  poetry-install:
    if: github.event.pull_request.draft == false
    uses: ./.github/workflows/poetry-install.yml
    secrets: inherit

  lint-code:
    needs: poetry-install
    uses: ./.github/workflows/lint.yml
    secrets: inherit

  unit-test:
    needs: poetry-install
    uses: ./.github/workflows/unit-test.yml
    secrets: inherit

  integration-test:
    needs: poetry-install
    # Exit if its a commit from Gitbook
    if: ${{ ! startsWith(github.event.head_commit.message, 'GitBook:') }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ["3.8", "3.9", "3.10"]
        test_environment:
          [
            "default",
            "docker-server-docker-orchestrator",
            "default-kubeflow-orchestrator",
          ]
        exclude:
          # docker and kubeflow are not supported on windows
          - os: windows-latest
            test_environment: default-kubeflow-orchestrator
          - os: windows-latest
            test_environment: docker-server-docker-orchestrator
          # kubeflow is time-consuming to run, so we only run it on 3.8
          - test_environment: default-kubeflow-orchestrator
            python-version: "3.9"
          - test_environment: default-kubeflow-orchestrator
            python-version: "3.10"
          # docker is time-consuming to run, so we only run it on 3.8
          - test_environment: docker-server-docker-orchestrator
            python-version: "3.9"
          - test_environment: docker-server-docker-orchestrator
            python-version: "3.10"
          # disable docker macos tests for now
          - test_environment: docker-server-docker-orchestrator
            os: macos-latest
          - test_environment: default-kubeflow-orchestrator
            os: macos-latest
          # disable kubeflow tests for now
          - test_environment: default-kubeflow-orchestrator

      fail-fast: false

    uses: ./.github/workflows/integration-test.yml
    with:
      os: ${{ matrix.os }}
      python-version: ${{ matrix.python-version }}
      test_environment: ${{ matrix.test_environment }}
    secrets: inherit

  markdown-link-check:
    uses: ./.github/workflows/markdown-link-check.yml

  spell-check:
    uses: ./.github/workflows/spellcheck.yml
