name: Build, Lint, Unit, Integration and Templates Tests

on:
  workflow_dispatch:
  workflow_call:
  push:
    branches: ["main", "develop"]
    paths-ignore: ["docs/**", "docker/**", "*", "!pyproject.toml", "**.md"]
  pull_request:
    types: [opened, synchronize, ready_for_review]
    paths-ignore: ["docs/**", "docker/**", "*", "!pyproject.toml", "**.md"]

concurrency:
  # New commit on branch cancels running workflows of the same branch
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ubuntu-setup-and-test-python:
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.8", "3.9", "3.10", "3.11"]
      fail-fast: false
    uses: ./.github/workflows/setup-python-environment.yml
    with:
      python-version: ${{ matrix.python-version }}
      os: ${{ matrix.os }}
    secrets: inherit

  windows-setup-and-test-python:
    strategy:
      matrix:
        os: [windows-latest]
        python-version: ["3.8", "3.9", "3.10", "3.11"]
      fail-fast: false
    uses: ./.github/workflows/setup-python-environment.yml
    with:
      python-version: ${{ matrix.python-version }}
      os: ${{ matrix.os }}
    secrets: inherit

  macos-setup-and-test-python:
    strategy:
      matrix:
        os: [macos-latest]
        python-version: ["3.8", "3.9", "3.10", "3.11"]
      fail-fast: false
    uses: ./.github/workflows/setup-python-environment.yml
    with:
      python-version: ${{ matrix.python-version }}
      os: ${{ matrix.os }}
    secrets: inherit

  ubuntu-integration-test:
    needs: 
      - ubuntu-setup-and-test-python
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.8", "3.9", "3.10", "3.11"]
        test_environment:
          [
            "default",
            "docker-server-docker-orchestrator",
          ]
        exclude:
          # docker is time-consuming to run, so we only run it on 3.8
          - test_environment: docker-server-docker-orchestrator
            python-version: "3.9"
          - test_environment: docker-server-docker-orchestrator
            python-version: "3.10"
          - test_environment: docker-server-docker-orchestrator
            python-version: "3.11"

      fail-fast: false

    uses: ./.github/workflows/integration-test.yml
    with:
      os: ${{ matrix.os }}
      python-version: ${{ matrix.python-version }}
      test_environment: ${{ matrix.test_environment }}
    secrets: inherit

  windows-integration-test:
    needs: 
      - windows-setup-and-test-python
    strategy:
      matrix:
        os: [windows-latest]
        python-version: ["3.8", "3.9", "3.10", "3.11"]
        test_environment: ["default"]

      fail-fast: false

    uses: ./.github/workflows/integration-test.yml
    with:
      os: ${{ matrix.os }}
      python-version: ${{ matrix.python-version }}
      test_environment: ${{ matrix.test_environment }}
    secrets: inherit

  macos-integration-test:
    needs: 
      - macos-setup-and-test-python
    strategy:
      matrix:
        os: [macos-latest]
        python-version: ["3.8", "3.9", "3.10", "3.11"]
        test_environment: ["default"]

      fail-fast: false

    uses: ./.github/workflows/integration-test.yml
    with:
      os: ${{ matrix.os }}
      python-version: ${{ matrix.python-version }}
      test_environment: ${{ matrix.test_environment }}
    secrets: inherit

  ubuntu-templates-test:
    needs:
      - ubuntu-setup-and-test-python
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.8", "3.9", "3.10", "3.11"]
      fail-fast: false
    uses: ./.github/workflows/templates-test.yml
    with:
      os: ${{ matrix.os }}
      python-version: ${{ matrix.python-version }}
    secrets: inherit

  windows-templates-test:
    needs: 
      - windows-setup-and-test-python
    strategy:
      matrix:
        os: [windows-latest]
        python-version: ["3.8", "3.9", "3.10", "3.11"]
      fail-fast: false
    uses: ./.github/workflows/templates-test.yml
    with:
      os: ${{ matrix.os }}
      python-version: ${{ matrix.python-version }}
    secrets: inherit

  macos-templates-test:
    needs:
      - macos-setup-and-test-python
    strategy:
      matrix:
        os: [macos-latest]
        python-version: ["3.8", "3.9", "3.10", "3.11"]
      fail-fast: false
    uses: ./.github/workflows/templates-test.yml
    with:
      os: ${{ matrix.os }}
      python-version: ${{ matrix.python-version }}
    secrets: inherit
