# This is a basic workflow to help you get started with Actions
name: CI

# Controls when the action will run. Triggers the workflow on push of a tag
on:
  push:
    tags:
      - '*'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  publish:
    name: Build and publish Python ðŸ distributions ðŸ“¦ to PyPI
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@master
      - name: local-fix
        run: |
          # Hack to get setup-python to work with act locally (see https://github.com/nektos/act/issues/251)
          if [ ! -f "/etc/lsb-release" ] ; then
            echo "DISTRIB_RELEASE=18.04" > /etc/lsb-release
          fi
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7

      # Runs a single command using the runners shell
      - name: install requirements
        run: sudo apt-get update && sudo apt-get install -y make && pip install twine

      # Run script directly
      - name: testing
        run: |
          pip install -e .[all]
          pip install pytest
          cd tests
          ./testing.sh
          cat ~/.config/zenml/info.json

      # Runs a set of commands using the runners shell
      - name: publish
        if: ${{ !env.ACT }}  # we dont want this tested locally with [act](https://github.com/nektos/act)
        env: # Or as an environment variable
          TWINE_NON_INTERACTIVE: ${{ secrets.TWINE_NON_INTERACTIVE }}
          TWINE_PASSWORD: ${{ secrets.TWINE_PASSWORD }}
          TWINE_USERNAME: ${{ secrets.TWINE_USERNAME }}
        run: |
          if [ "$(cat zenml/VERSION)" = "$(echo ${GITHUB_REF} | sed 's|refs/tags/||g')" ]; then make publish; else exit 1; fi