---
# https://github.com/marketplace/actions/team-labeler-action
# https://github.com/TimonVS/pr-labeler-action
on:
  pull_request:
    types: [opened]
name: pr-label
jobs:
  pr-labeler:
    if: github.repository == 'zenml-io/zenml'
    runs-on: ubuntu-latest
    env:
      ZENML_DEBUG: 1
      ZENML_ANALYTICS_OPT_IN: false
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: JulienKode/team-labeler-action@a205b2457cc66b356257560e3c7bb853a9e8199e  # v1.1.0
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - uses: TimonVS/pr-labeler-action@8b99f404a073744885d8021d1de4e40c6eaf38e2  # v4.1.1
        with:
          configuration-path: .github/branch-labels.yml
