---
# package and push the zenml helm chart to the ECR repository
name: Publish Helm Chart
on:
  workflow_call:
  workflow_dispatch:
jobs:
  publish_to_ecr:
    name: Publish Helm Chart üõû to ECR ‚òÅÔ∏è
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    env:
      ZENML_DEBUG: 1
      ZENML_ANALYTICS_OPT_IN: false
      PYTHONIOENCODING: utf-8
    steps:
      - name: Checkout repo
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  # v4.2.2

      # The following sed command replaces the version number in Chart.yaml with the tag version.
      # It replaces the line that starts with "version: " with "version: <tag version>"
      - name: Add tag version to Chart.yaml
        run: |
          sed -i "s/version: .*/version: \"${GITHUB_REF_NAME}\"/" helm/Chart.yaml
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@5fd3084fc36e372ff1fff382a39b10d03659f355  # v2
        with:
          role-to-assume: arn:aws:iam::715803424590:role/gh-action-role-zenml-helm
          aws-region: us-east-1
      - name: Login to Amazon ECR Public
        id: login-ecr-public
        uses: aws-actions/amazon-ecr-login@062b18b96a7aff071d4dc91bc00c4c1a7945b076  # v2
        with:
          mask-password: 'true'
          registry-type: public

      # TODO: revisit the pinned helm version + find a higher version
      - name: install helm with version 3.9.2
        uses: azure/setup-helm@5119fcb9089d432beecbf79bb2c7915207344b78  # v3.5
        with:
          version: v3.9.2  # default is latest (stable)
        id: install-helm
      - name: Package and push helm chart to Amazon ECR Public
        env:
          REGISTRY: ${{ steps.login-ecr-public.outputs.registry }}
          REGISTRY_ALIAS: zenml
          REPOSITORY: zenml
        run: |-
          helm package ./helm
          helm push $REPOSITORY-${GITHUB_REF_NAME}.tgz oci://$REGISTRY/$REGISTRY_ALIAS
