---
name: Publish SDK Docs
on:
  push:
    branches: [release/**]
jobs:
  publish:
    name: Build üî® and publish üì∞ the api docs üìÅ to gh-pages
    if: github.repository == 'zenml-io/zenml'
    runs-on: ubuntu-latest
    env:
      ZENML_DEBUG: 1
      ZENML_ANALYTICS_OPT_IN: false
      PYTHONIOENCODING: utf-8
    steps:
      - uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 0  # fetch all commits/branches including gh-pages
      - name: Get the version from the github branch name
        id: get_version
        run: |
          BRANCH='${{github.ref_name}}'
          echo ::set-output name=VERSION::${BRANCH#release/}
      - uses: actions/setup-node@v4.0.1
        with:
          node-version: '14'
      - run: npm install
      - run: npm install html-minifier -g
      - name: Set up Python 3.11
        uses: actions/setup-python@v5.3.0
        with:
          python-version: '3.11'
      - name: Setup git user
        run: |
          git config --global user.name 'Code Monkey'
          git config --global user.email 'codemonkey@zenml.io'
      - name: Runs docs generation
        run: |-
          bash scripts/generate-docs.sh -s src/zenml/ --push --latest -v ${{ steps.get_version.outputs.VERSION }}
