# This is a basic workflow that publishes the website
name: Publish API Docs

# Controls when the action will run.
on:
  push:
    branches:
      - "release/**"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "publish"
  publish:
    name: Build üî® and publish üì∞ the api docs üìÅ to gh-pages
    runs-on: ubuntu-latest
    env:
      ZENML_DEBUG: 1
      ZENML_ANALYTICS_OPT_IN: false
      PYTHONIOENCODING: "utf-8"

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 # fetch all commits/branches including gh-pages

      - name: Get the version from the github branch name
        id: get_version
        run: |
          BRANCH='${{github.ref_name}}'
          echo ::set-output name=VERSION::${BRANCH#release/}

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - uses: actions/setup-node@v2
        with:
          node-version: "14"
      - run: npm install
      - run: npm install html-minifier -g

      - name: Setup environment with Poetry
        uses: ./.github/actions/setup_environment
        with:
          cache_version: ${{ secrets.GH_ACTIONS_CACHE_KEY }}

      # IMPORTANT: there's a strategy to installing integrations here in a way
      # that avoids conflicts while at the same time making it possible for all
      # ZenML Python modules to be imported, especially the integration modules:
      # 1. install zenml with all extras with poetry
      # 2. install more restrictive integrations first: feast, seldon and
      # label_studio are currently the ones known to be very restrictive in
      # terms of what versions of dependencies they require
      # 3. install the rest of the integrations
      # 4. as the last step, install zenml again (step 1. repeated)
      - name: Install Dependencies
        run: |
          source $VENV
          zenml integration install -y feast
          zenml integration install -y label_studio seldon
          zenml integration install -y --ignore-integration feast --ignore-integration label_studio --ignore-integration seldon
          poetry install --extras server

      - name: Setup git user
        run: |
          git config --global user.name 'Code Monkey'
          git config --global user.email 'codemonkey@zenml.io'

        # env.py leads to errors in the build as run_migrations() gets executed
        # the migration versions are not necessary parts of the api docs
      - name: Delete unnecessary alembic files
        run: |
          rm -rf src/zenml/zen_stores/migrations/env.py
          rm -rf src/zenml/zen_stores/migrations/versions
          rm -rf src/zenml/zen_stores/migrations/script.py.mako

      - name: Runs docs generation
        run: poetry run bash scripts/generate-docs.sh -s src/zenml/ --push --latest -v ${{ steps.get_version.outputs.VERSION }}
