# This is a basic workflow to help you get started with Actions
name: Pull Request

# Controls when the action will run. Triggers the workflow on pull request
on: pull_request

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  testing:
    name: Build and test ZenML on Python ðŸ distributions
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@master
      - name: local-fix
        run: |
          # Hack to get setup-python to work with act locally (see https://github.com/nektos/act/issues/251)
          if [ ! -f "/etc/lsb-release" ] ; then
            echo "DISTRIB_RELEASE=18.04" > /etc/lsb-release
          fi
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7

      # Run script directly
      - name: testing
        run: |
          pip install -e .[all]
          pip install pytest
          cd tests
          ./testing.sh
          cat ~/.config/zenml/info.json
