# This is a basic workflow to help you get started with Actions
name: Release Package & Docker Image

# Controls when the action will run. Triggers the workflow on push of a tag
on:
  push:
    tags:
      - '*'

jobs:

  lint-unit-test:
    uses: ./.github/workflows/lint-unit-test.yml
    with:
      os: "ubuntu-latest"
      python-version: "3.8"
    secrets: inherit

  compatibility-check:
    needs: lint-unit-test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"

      - name: Install current package as editable
        run: pip install -e .

      - name: Install mlstacks package
        run: pip install mlstacks

      - name: Check for broken dependencies
        run: pip check

  publish-python-package:
    needs: [lint-unit-test, compatibility-check]
    uses: ./.github/workflows/publish_to_pypi.yml
    secrets: inherit

  wait-for-package-release:
    runs-on: ubuntu-latest
    needs: publish-python-package
    steps:
      - name: Sleep for 3 minutes
        run: sleep 180
        shell: bash

  publish-docker-image:
    needs: wait-for-package-release
    uses: ./.github/workflows/publish_docker_image.yml
    secrets: inherit
