# This is a basic workflow to help you get started with Actions
name: Release Package & Docker Image

# Controls when the action will run. Triggers the workflow on push of a tag
on:
  push:
    tags:
      - '*'

jobs:

  lint-unit-test:
    uses: ./.github/workflows/lint-unit-test.yml
    with:
      os: "ubuntu-latest"
      python-version: "3.8"
    secrets: inherit

  publish-python-package:
    needs: lint-unit-test
    uses: ./.github/workflows/publish_to_pypi.yml
    secrets: inherit

  wait-for-package-release:
    runs-on: ubuntu-latest
    needs: publish-python-package
    steps:
      - name: Sleep for 3 minutes
        run: sleep 180
        shell: bash

  publish-docker-image:
    needs: wait-for-package-release
    uses: ./.github/workflows/publish_docker_image.yml
    secrets: inherit

  publish-helm-chart:
    needs: publish-docker-image
    uses: ./.github/workflows/publish_helm_chart.yml
    secrets: inherit
