name: Update Tutorials

on:
  pull_request:
    branches:
      - develop
    paths:
      - 'tutorials/**'

jobs:
  update-tutorials:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
    - name: Checkout code
      uses: actions/checkout@v4.1.1
      with:
        fetch-depth: 0  # Fetch all history for all branches and tags

    - name: Set up Python 3.9
      uses: actions/setup-python@v5.0.0
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install nbconvert pyyaml jupyter

    - name: Clear notebook outputs
      run: |
        find tutorials -name "*.ipynb" -exec jupyter nbconvert --ClearOutputPreprocessor.enabled=True --inplace {} \;
    
    - name: Update Tutorials
      id: update_tutorials
      run: python scripts/update_tutorials.py
    
    - name: Configure Git
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"

    - name: Commit changes
      run: |
        git add tutorials docs/book
        git diff-index --quiet HEAD || git commit -m "Update Tutorial content and clear notebook outputs"

    - name: Fetch latest changes
      run: git fetch origin ${{ github.head_ref }}

    - name: Merge latest changes
      run: |
        git checkout ${{ github.head_ref }}
        git merge --no-edit origin/${{ github.head_ref }}

    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.head_ref }}

    - name: Create PR comment
      if: success()
      uses: actions/github-script@v7
      with:
        github-token: ${{secrets.GITHUB_TOKEN}}
        script: |
          const prNumber = context.payload.pull_request.number;
          console.log(`PR number: ${prNumber}`);
          
          try {
            await github.rest.issues.createComment({
              issue_number: prNumber,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'The tutorials content has been successfully updated.'
            });
          } catch (error) {
            console.error('Error creating comment:', error);
            core.setFailed(`Failed to create comment: ${error.message}`);
          }

    - name: Create PR comment on failure
      if: failure()
      uses: actions/github-script@v7
      with:
        github-token: ${{secrets.GITHUB_TOKEN}}
        script: |
          const prNumber = context.payload.pull_request.number;
          console.log(`PR number: ${prNumber}`);
          
          try {
            await github.rest.issues.createComment({
              issue_number: prNumber,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'There was an error updating the tutorial content. Please check the workflow logs for more information.'
            });
          } catch (error) {
            console.error('Error creating comment:', error);
            core.setFailed(`Failed to create comment: ${error.message}`);
          }